//! Helper functions for `keel init` — language detection, gitignore, keelignore, telemetry ID.

use std::fs;
use std::path::Path;

/// Detect which languages are present by scanning file extensions.
pub fn detect_languages(root: &Path) -> Vec<String> {
    let mut langs = std::collections::HashSet::new();

    let walker = keel_parsers::walker::FileWalker::new(root);
    for entry in walker.walk() {
        if !langs.contains(&entry.language) {
            langs.insert(entry.language);
        }
    }

    let mut result: Vec<String> = langs.into_iter().collect();
    result.sort();
    result
}

/// Ensure `.gitignore` contains keel-specific entries.
pub fn update_gitignore(root: &Path, verbose: bool) {
    let gitignore_path = root.join(".gitignore");
    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();

    let entries = [
        ".keel/graph.db",
        ".keel/telemetry.db",
        ".keel/session.json",
        ".keel/last_compile.json",
        ".keel/compile.lock",
        ".keel/cache/",
    ];

    let mut missing: Vec<&str> = Vec::new();
    for entry in &entries {
        if !existing.lines().any(|line| line.trim() == *entry) {
            missing.push(entry);
        }
    }

    if missing.is_empty() {
        return;
    }

    let mut content = existing;
    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str("\n# keel (generated by keel init)\n");
    for entry in &missing {
        content.push_str(entry);
        content.push('\n');
    }

    match fs::write(&gitignore_path, content) {
        Ok(_) => {
            if verbose {
                eprintln!(
                    "keel init: updated .gitignore with {} keel entries",
                    missing.len()
                );
            }
        }
        Err(e) => {
            eprintln!("keel init: warning: failed to update .gitignore: {}", e);
        }
    }
}

/// Generate a stable telemetry ID for project deduplication.
/// Uses xxhash with hostname, PID, timestamp, and path as entropy sources
/// to produce a unique 32-hex-char identifier without requiring a `rand` dep.
pub fn generate_telemetry_id(root: &Path) -> String {
    let hostname = std::fs::read_to_string("/etc/hostname")
        .unwrap_or_default()
        .trim()
        .to_string();
    let pid = std::process::id();
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let entropy = format!("{}:{}:{}:{}", hostname, pid, timestamp, root.display());
    let hi = xxhash_rust::xxh64::xxh64(entropy.as_bytes(), 0);
    let lo = xxhash_rust::xxh64::xxh64(entropy.as_bytes(), 42);
    format!("{:016x}{:016x}", hi, lo)
}

/// Create a default .keelignore file if one doesn't exist.
pub fn create_keelignore(root: &Path, verbose: bool) {
    let ignore_path = root.join(".keelignore");
    if ignore_path.exists() {
        return;
    }

    let default_patterns = "\
node_modules/
__pycache__/
target/
dist/
build/
.next/
.svelte-kit/
vendor/
.venv/
";

    match fs::write(&ignore_path, default_patterns) {
        Ok(_) => {
            if verbose {
                eprintln!("keel init: created .keelignore");
            }
        }
        Err(e) => {
            eprintln!("keel init: warning: failed to create .keelignore: {}", e);
        }
    }
}
