// Tests for instruction file generation (Spec 009)
//
// Validates that keel generates correct instruction files (CLAUDE.md, AGENTS.md,
// .windsurfrules, .github/copilot-instructions.md) for various AI coding tools.
//
// use keel_cli::integration::instructions::{generate_claude_md, generate_agents_md,
//     generate_windsurfrules, generate_copilot_instructions};
// use std::path::Path;
// use std::fs;

#[test]
#[ignore = "Not yet implemented"]
fn test_claude_md_generation() {
    // GIVEN a keel-initialized project directory
    // WHEN CLAUDE.md instruction file is generated
    // THEN the file contains keel-specific instructions for Claude Code sessions
}

#[test]
#[ignore = "Not yet implemented"]
fn test_claude_md_includes_compile_workflow() {
    // GIVEN a generated CLAUDE.md file
    // WHEN the content is examined
    // THEN it includes instructions to run `keel compile` after editing source files
}

#[test]
#[ignore = "Not yet implemented"]
fn test_agents_md_generation() {
    // GIVEN a keel-initialized project directory
    // WHEN AGENTS.md instruction file is generated
    // THEN the file contains generic agent instructions for keel enforcement
}

#[test]
#[ignore = "Not yet implemented"]
fn test_windsurfrules_generation() {
    // GIVEN a keel-initialized project directory
    // WHEN .windsurfrules instruction file is generated
    // THEN the file contains Windsurf-specific rules for keel enforcement
}

#[test]
#[ignore = "Not yet implemented"]
fn test_copilot_instructions_generation() {
    // GIVEN a keel-initialized project directory
    // WHEN .github/copilot-instructions.md is generated
    // THEN the file contains GitHub Copilot-specific instructions for keel
}

#[test]
#[ignore = "Not yet implemented"]
fn test_instruction_files_include_error_codes() {
    // GIVEN any generated instruction file (CLAUDE.md, AGENTS.md, etc.)
    // WHEN the content is examined
    // THEN it includes descriptions of error codes E001-E005 and warnings W001-W002
}

#[test]
#[ignore = "Not yet implemented"]
fn test_instruction_files_merge_with_existing() {
    // GIVEN a project with an existing CLAUDE.md containing user-written instructions
    // WHEN keel instruction generation is run
    // THEN the existing content is preserved and keel section is appended/updated
}

#[test]
#[ignore = "Not yet implemented"]
fn test_instruction_files_idempotent() {
    // GIVEN a project where instruction files have already been generated by keel
    // WHEN instruction generation is run again
    // THEN the files are identical (no duplicate sections, idempotent update)
}
